# Generated by Django 4.2.1 on 2023-05-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0002_acessorio_cor_veiculo_marca_nacionalidade_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cor",
            options={"verbose_name_plural": "cores"},
        ),
        migrations.AddField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="preco",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
